vich_uploader:
    db_driver: orm

    mappings:
        poster_file:
            uri_prefix: /uploads/posters
            upload_destination: '%kernel.project_dir%/public/uploads/posters'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
